export enum WarningType {
    NOT_DOWNLOADED = 'NOT DOWNLOADED',
    VIDEO_UNAVAILABLE = 'VIDEO UNAVAILABLE',
    CANNOT_DELETE_FROM_PLAYLIST = 'CANNOT DELETE FROM PLAYLIST',
    ESSENTIA_ERROR = 'ESSENTIA ERROR',
    NOTION_ADD_ROW_ERROR = 'NOTION ADD ROW ERROR',
    DROPBOX_UPLOAD_ERROR = 'DROPBOX UPLOAD ERROR',
    DROPBOX_CREATE_SHARING_LINK_ERROR = 'DROPBOX CREATE SHARING LINK ERROR',
    NOTION_DROPBOX_LINK_ERROR = 'NOTION DROPBOX LINK ERROR',
    ERROR = 'ERROR',
}