export enum WarningType {
    NOT_DOWNLOADED = 'NOT DOWNLOADED',
    VIDEO_UNAVAILABLE = 'VIDEO UNAVAILABLE',
    CANNOT_DELETE_FROM_PLAYLIST = 'CANNOT DELETE FROM PLAYLIST',
    CANNOT_ADD_TO_PLAYLIST = 'CANNOT ADD TO PLAYLIST',
    ESSENTIA_ERROR = 'ESSENTIA ERROR',
    NOTION_ADD_ROW_ERROR = 'NOTION ADD ROW ERROR',
    ERROR = 'ERROR',
}